version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: prestamos-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestamos_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: prestamos-backend
    volumes:
      - ./docker/scripts/clone_backend.sh:/usr/local/bin/clone_backend.sh
      - ./backend:/var/www/backend   # opcional
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    command: ["bash", "/usr/local/bin/clone_backend.sh"]

  frontend:
    image: node:20
    container_name: prestamos-frontend
    working_dir: /var/www
    volumes:
      - ./docker/scripts/clone_frontend.sh:/usr/local/bin/clone_frontend.sh
      - ./frontend:/var/www/frontend   # opcional
    depends_on:
      - backend
    ports:
      - "8001:8001"
    command: ["bash", "/usr/local/bin/clone_frontend.sh"]

volumes:
  mysql_data:
