services:

  mysql:
    image: mysql:8.0
    container_name: prestamos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestamos_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - prestamos-net

  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: prestamos-backend
    volumes:
      - ./backend:/var/www/backend
      - ./docker/scripts/clone_backend.sh:/usr/local/bin/clone_backend.sh
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    command: bash /usr/local/bin/clone_backend.sh
    networks:
      - prestamos-net

  frontend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.frontend
    container_name: prestamos-frontend
    volumes:
      - ./frontend:/var/www/frontend
      - ./docker/scripts/clone_frontend.sh:/usr/local/bin/clone_frontend.sh
    depends_on:
      - mysql
    ports:
      - "8001:8001"
      - "5173:5173"
    command: bash /usr/local/bin/clone_frontend.sh
    networks:
      - prestamos-net

volumes:
  mysql_data:

networks:
  prestamos-net:
    driver: bridge
